### ISSUE TITLE
"AttributeError: Item has no attribute subclass_information .." => Attribute lists ?

### ISSUE THREAD

**Issue by Fxztam** [LatvianPython/pyoracle_forms#15]
I begin with pyoracle_forms, the tests and the font demo works for me;
many thanks for this work!

Now I am trying to use Oracle Forms attributes and have a problem 
with the ` item.sublass_information ` : _AttributeError: Item has no attribute subclass_information'_.

Is there any chance to solve this for subclasses and where can I get the attribute lists used from pyoracle_forms?

Fried

**Comment by LatvianPython** [comment]
👋 hey, good to hear that someone is using this, or at least trying to use it.

I do not actually think subclasses are implemented, they are not classic attributes that items/canvases/data blocks/etc. have.

If you take a look at what attributes you have for items, I do not see anything that would be related to subclasses, see https://pastebin.com/nc2HvxNy (added in pastebin as otherwise too many attributes just for a comment)

Can you say what you are trying to do with subclasses? Maybe I can try to implement this as a feature for you in the package.

Oracle has a couple functions in the C Oracle Forms API that may do what you want, can you check if any of these would help you?

```
**  d2fobsc_SubClass - Change the subclassing parent of an object to the
**                   specified parent object.  Note that this will cause
**                   local property values in the child object to be
**                   removed for all properties which are defined on the
**                   parent object.  The keep_path argument indicates
**                   whether the system should refer to the parent object's
**                   module by filename along or by path+filename.  The
**                   recommended choice is FALSE for this argument in most
**                   cases.
**
**  d2fobus_UnSubClass - Un-subclass an object if it is subclassed.
**
**  d2fobis_IsSubclassed - Returns D2FS_YES or D2FS_NO depending on whether
**                   the object has a subclassing source object from which
**                   it may inherit property values.
**
**  d2fobre_Replicate - Creates a new object with a the given name and given
**                   owning object.  The new object is an exact copy of the
**                   original object, with all the same property values, and
**                   all the same subclassing relations.  Returns D2FS_FAIL
**                   if the system is unable to duplicate the entire object.
**                   Compare to the Duplicate() function which flattens the
**                   property values so that everything becomes local to the
**                   new object.
**
**  d2fobra_Reattach - This function resets the source of the given object
**                   to match its internal source info.  This is intended
**                   for hooking up subclassing relations after the source
**                   info has been directly modified.  This is primarily an
**                   internal function, but may have external uses in some
**                   cases.
```

There are some other functions in their API, but those are related with property inheritance, see:

```
**  d2fobip_InheritProp - Remove any local value for the specified
**                   property, effectively forcing the object to inherit
**                   the property value from its subclassing source, if
**                   it has one.
**
**  d2fobii_IspropInherited - Returns D2FS_YES or D2FS_NO depending on
**                   whether the given object is inheriting the specified
**                   property from a subclassing source object.  This is
**                   different than d2fobid_IspropDefault() because this
**                   function only returns YES when the given object has
**                   no local value, but is inheriting a non-default value
**                   from its subclassing source.
**
**  d2fobid_IspropDefault - Returns D2FS_YES or D2FS_NO depending on whether
**                   the object has a LOCAL value for the specified
**                   property.  If the object has a local value, then the
**                   function returns D2FS_NO since the property is not
**                   default-valued.  If the object has no local value,
**                   which means the object is either inheriting a value,
**                   or picking up the system default value, then this
**                   function returns D2FS_YES.```

**Comment by LatvianPython** [comment]
> where can I get the attribute lists used from pyoracle_forms

 Did you mean a list of available attributes for objects?

If so, then you can check this by calling the built-in `dir` function in Python,  https://docs.python.org/3/library/functions.html#dir

The return value will include all available attributes, this is how I get the list that I posted to pastebin.

**Comment by LatvianPython** [comment]
Oh, I think I misunderstood at the start what you were asking, it was not necessarily about subclasses, but you wanted to find out how to determine which Oracle Forms object attributes are available for any of the object type used by forms, correct?

If that was the question, well, then right now you basically have to use the `dir` function, I suggest using an interactive environment like Jupyter just to experiment first with the package, figure out what has which attributes. 

I do not have it setup such that you have IDE autocomplete for all possible objects used in forms, I have this for the `Module` class, you can check that here in the code https://github.com/LatvianPython/pyoracle_forms/blob/bdf7efc8c5a8ea33caf45fcf58f57c4b2bb00daf/pyoracle_forms/forms_objects.py#L15-L25

This is then used by the IDE, but takes time for me to write. I did think about some automated way of doing this, I may look into it again if it would help. ✌️ 

The problem with having all attributes available for autocomplete in my view was that not all attributes are supported by all versions, so I did not focus on that, but I suppose I can make it so that all attributes are available for autocomplete, but then during runtime you just get an error if it is not supported by the version you are using.

**Comment by Fxztam** [comment]
👋thank you for your quick and really helpful reply. 

_@Did you mean a list of available attributes for objects?_
:: Yes, I will try the `built-in dir` function in Python and your attributes list in pastebin helps me a lot, exactly what I meant.

_@Oh, I think I misunderstood_  
:: No, you understood me very well, I would like to change the Item's ` Subclassing Information ` e.g. from `Dark` to `Light` :

![image](https://user-images.githubusercontent.com/5808032/164890367-b7b1d5c1-436f-4715-add4-0136266caeb5.png)

Yesterday I tried it in JDAPI - Java:
![image](https://user-images.githubusercontent.com/5808032/164890940-5432e7c3-9014-4cc2-8136-319a941b243d.png)

That's why the CAPI  ` d2fobsc_SubClass ` seems the right point to me and
it would be great to read & change it by pyoracle_forms.

My motivation is to change the basic layout of a Forms module and
later you could build module templates incl. referenced PLL & OLB libs and objects.

Here is my native Oracle Forms demo: 

![image](https://user-images.githubusercontent.com/5808032/164891055-78dd02d3-5c95-4609-95f9-18116580ae02.png)

Fried

PS: I have worked with some JDAPI PoC in Jython before:
[https://github.com/Fxztam/FormsJDAPIwJython/blob/master/FormsExtractCode.py](url)
[https://www.fmatz.com/set_version4forms.jy](url)

**Comment by LatvianPython** [comment]
Problem for me is not having a good example to test on that uses subclasses and property classes, I'll try to get something together, a minimal example to test on. The form that I have I think has one property class. 

If you can provide me your demo form, then it would help me out a ton, I'll see if I can get something together myself as well.

Can you check for me in your form, can you see the property classes under the forms module in the `property_classes` attribute?

Can you try to run this script, it should at least print out the available property classes for your form, PC_CANVAS_DARK, PC_ITEM_DARK, etc.:

```python
from pyoracle_forms import Module, initialize_context
initialize_context(version="12c", encoding="utf-8")

with Module.load("./your_form.fmb") as module:
    for property_class in module.property_classes:
        print(property_class, property_class.name)
```

Above script will not help in figuring out what each item has as its subclass, I will look into where that info is available, does not seem the C API function have this, the ones I posted were only about either adding subclass parent, or removing it, have yet to find how to inspect current subclass.

Anyway, like I mentioned, I'll see what I can do, adding an option to add property class for an object to use seems simple, just need to implement the API function in the package, the other part about being able to check what property class is used for current item, will need some investigation. ✌️

**Comment by LatvianPython** [comment]
Ok, so I made a test just now, turns out you can get info about property classes for items in the current version, you can check attribute `source_object`, and it will give you the property class object, which you then can check.

For example:

```python
from pyoracle_forms import Module, initialize_context
initialize_context(version="12c", encoding="utf-8")

with Module.load("./tests/test_modules/property_classes.fmb") as module:
    for data_block in module.data_blocks:
        for item in data_block.items:
            print(data_block.name, item.name, item.source_object.name)
```
Should print out, all items, and which property class they use :v:

You may also then be interested in these attributes, also related with the source object (subclass information):

```
parent_object_name
parent_objects_file_name
parent_objects_file_path
parent_objects_first_level_owners_name
parent_objects_first_level_owners_type
parent_objects_module
parent_objects_module_type
parent_objects_type
```

`item.parent_object_name` gives you the same result as `item.source_object.name`, just that the latter one gives you the actual property class object, I suppose Oracle gives you `parent_object_name` as a shortcut.

I'll then just see about adding a way to set, and remove property classes.

**Comment by LatvianPython** [comment]
Update the package from PyPi, new version is v0.3.1, added new functions for objects, `subclass` and `un_subclass`

You can check the new tests I wrote to how the functions can be used, for adding a subclass you need to pass the "Property class" object you get from the form module in the `module.property_classes` list, to remove existing one, you just call `un_subclass` on the object you want the subclass information to be removed from.

https://github.com/LatvianPython/pyoracle_forms/blob/28983ca657cfae24ebcbdcf88d53e5509ad8ab70/tests/test_subclass.py#L1-L13

Let me know if this helps

**Comment by Fxztam** [comment]
Thanks very much,

- I actualized to version 0.3.1 and the tests run successfully incl. `test_subclass.py`

- `print(data_block.name, item.name, item.source_object.name)` does not work for me
   => `AttributeError: 'int' object has no attribute 'name' ` => `item.source_object.name`

- I cannot use `item.subclass(property_class)` => `AttributeError: 'Item' object has no attribute 'subclass' `

- here is my module: [https://www.fmatz.com/my-dapi-test.fmb](url) 

- can you create a code snipped for `set_subclass(item, property_class` & `remove_subclass(item)` please ?

Great.

**Comment by LatvianPython** [comment]
```python
from pyoracle_forms import Module, initialize_context, __version__
initialize_context(version="12c", encoding="utf-8")

def find_property_class(module, property_class_name):
    for property_class in module.property_classes:
        if property_class.name == property_class_name:
            return property_class
        
    return None

print(__version__)

with Module.load("my-dapi-test.fmb") as module:
    property_class = find_property_class(module, "PC_ITEM_DARK")
    
    if property_class:
        for data_block in module.data_blocks:
            for item in data_block.items:
                item.subclass(property_class)
                print(f"{item.name} -> {item.source_object.name}")
```

Tested snippet on your form, should print out:

```
0.3.1
ITEM4 -> PC_ITEM_DARK
ITEM5 -> PC_ITEM_DARK
ITEM6 -> PC_ITEM_DARK
ITEM7 -> PC_ITEM_DARK
ITEM3 -> PC_ITEM_DARK
```

**Comment by LatvianPython** [comment]
> can you create a code snipped for set_subclass(item, property_class & remove_subclass(item) please ?

`set_subclass`, and `remove_subclass` actually are much better names for the methods, will consider changing to this actually

**Comment by Fxztam** [comment]
You are right, in my PyCharm IDE worked the old version 0.2.10  :-{  , sorry!

Now, the issues above are working and all item have `PC_ITEM_DARK` !

Thanks again for your great work!

**Comment by LatvianPython** [comment]
Changed the methods to `set_subclass`, and `remove_subclass`, so if you update the package, make sure to update the code :v:
